---
title: "Blog"
---

**March 16, 2026**

After reading Jeff Leek's *How To Be A Modern Scientist*, I learned a lot from him. Currently as a student, I think that breaking into the academia world is incredibly daunting. However, from reading Leek's work I came out with a couple of takeaways.

The first being that post publication work is just as important. Even after publishing into a journal, there is still a lot of work that needs to be done. I had originally thought that the end goal was just to get published. However, publishing into a journal does not automatically mean that everyone has read it and so you have to continue advertising it and sharing the results.

The second being the emphasize on peer review. Work should not be completely one sided, but instead we should be asking others for their opinions so that we can put out the best paper possible. The structure that Leek spoke on was: comments to authors, comments to editors, and recommendations. This makes it very clear on what can be done to better the paper. As an added bonus to that, I think that it is very important for a scientist to be able to take criticism well, because peers are doing us a favor by reading our work and trying to make it better. There is no point in being offended by their good will since the end goal for everyone is to come out with a well written and scientifically based paper.
